version: '2'

services:
  demo:
    image: nginx
    volumes:
      - ".:/usr/share/nginx/html"
    ports:
      - "80:80"

  proxy:
    image: kuzzleio/proxy:1.0.0-RC9
    ports:
      - "7512:7512"

  kuzzle:
    image: kuzzleio/kuzzle:1.0.0-RC9
    depends_on:
      - proxy
      - redis
      - elasticsearch
    environment:
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=proxy
      - NODE_ENV=production

  redis:
    image: redis:3.2

  elasticsearch:
    image: elasticsearch:5.0
    command: elasticsearch --cluster.name=analytics
