demo:
  image: nginx
  volumes:
    - ".:/usr/share/nginx/html"
  links:
    - kuzzle
  ports:
    - "80:80"

kuzzle:
  image: kuzzleio/kuzzle:1.0.0-RC3
  volumes:
    - "./fixtures.json:/fixtures.json"
  ports:
    - "7512:7512"
  links:
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN=1
    - FIXTURES=/fixtures.json

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: elasticsearch:2.2
  command: elasticsearch --cluster.name=chat
