version: '2'

services:
  bootstrap:
    image: node:4
    working_dir: /var/app
    command: sh -c 'npm install -g bower && bower install --allow-root'
    volumes:
      - ".:/var/app"

  demo:
    image: nginx
    volumes:
      - ".:/usr/share/nginx/html"
    links:
      - kuzzle
    ports:
      - "80:80"

  proxy:
    image: kuzzleio/proxy:1.0.0-RC5
    networks:
      chat:
        aliases:
          - api
    ports:
      - "7511-7513:7511-7513"

  kuzzle:
    image: kuzzleio/kuzzle:1.0.0-RC6
    networks:
      - chat
    volumes:
      - "./fixtures.json:/fixtures.json"
      - "./pm2.json:/config/pm2.json"
    links:
      - elasticsearch
      - redis
      - proxy:api
    environment:
      - LIKE_A_VIRGIN=1
      - FIXTURES=/fixtures.json

  redis:
    image: redis:3.0-alpine
    networks:
      - chat

  elasticsearch:
    image: elasticsearch:2.2
    networks:
      - chat
    command: elasticsearch --cluster.name=chat

networks:
  chat:
