demo:
  image: nginx
  volumes:
    - ".:/usr/share/nginx/html"
  links:
    - kuzzle
  ports:
    - "80:80"

kuzzle:
  image: kuzzleio/kuzzle:beta
  volumes:
    - "./defaultMapping.json:/defaultMapping.json"
  ports:
    - "7512:7512"
  links:
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN=1
    - DEFAULT_MAPPING=/defaultMapping.json

redis:
  image: redis:3.0

elasticsearch:
  image: elasticsearch:1.7
  command: elasticsearch --cluster.name=planningpoker
