demo:
  image: nginx
  volumes:
    - ".:/usr/share/nginx/html"
  links:
    - kuzzle
  ports:
    - "80:80"

proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511:7511"
    - "7512:7512"
    
kuzzle:
  image: kuzzleio/kuzzle:1.0.0-RC4
  volumes:
    - "./defaultMapping.json:/defaultMapping.json"
  links:
    - elasticsearch
    - redis
    - proxy:api
  environment:
    - LIKE_A_VIRGIN=1
    - DEFAULT_MAPPING=/defaultMapping.json

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: elasticsearch:2.2
  command: elasticsearch --cluster.name=planningpoker
