demo:
  image: nginx
  volumes:
    - ".:/usr/share/nginx/html"
  links:
    - kuzzle
  ports:
    - "80:80"

kuzzle:
  image: kuzzleio/kuzzle:0.6.0
  ports:
    - "7512:7512"
  links:
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN=1

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2
  command: elasticsearch --cluster.name=paint
