demo:
  image: nginx
  volumes:
    - ".:/usr/share/nginx/html"
  ports:
    - "80:80"

kuzzle:
  image: kuzzleio/kuzzle:1.0.0-beta.1
  volumes:
    - "./fixtures.json:/fixtures.json"
  ports:
    - "7512:7512"
  links:
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN=1
    - FIXTURES=/fixtures.json

redis:
  image: redis:3.0

elasticsearch:
  image: elasticsearch:1.7
  command: elasticsearch --cluster.name=todolist
