version: '2'

services:
  bootstrap:
    image: node:4
    working_dir: /var/app
    command: sh -c 'npm install -g bower && bower install --allow-root'
    volumes:
      - ".:/var/app"

  demo:
    image: nginx
    volumes:
      - ".:/usr/share/nginx/html"
    ports:
      - "80:80"

  proxy:
    image: kuzzleio/proxy:1.0.0-RC5
    networks:
      todolist:
        aliases:
          - api
    ports:
      - "7511-7513:7511-7513"

  kuzzle:
    image: kuzzleio/kuzzle:1.0.0-RC6
    networks:
      - todolist
    volumes:
      - "./fixtures.json:/fixtures.json"
      - "./pm2.json:/config/pm2.json"

  redis:
    image: redis:3.2-alpine
    networks:
      - todolist

  elasticsearch:
    image: elasticsearch:2.2
    networks:
      - todolist
    command: elasticsearch --cluster.name=todolist

networks:
  todolist:
