version: '2'

services:
  demo:
    image: nginx
    networks:
      - tournament
    volumes:
      - ".:/usr/share/nginx/html"
    ports:
      - "80:80"
    environment:
      - KUZZLE_HOST

  server:
    image: node:4.1.1
    depends_on:
      - proxy
    networks:
      - tournament
    command: sh -c "cd /var/app && npm start"
    volumes:
      - ".:/var/app"

  proxy:
    image: kuzzleio/proxy:1.0.0-RC5
    networks:
      tournament:
        aliases:
          - api
    ports:
      - "7511-7513:7511-7513"

  kuzzle:
    image: kuzzleio/kuzzle:1.0.0-RC6
    networks:
      - tournament

  redis:
    image: redis:3.2-alpine
    networks:
      - tournament

  elasticsearch:
    image: elasticsearch:2.3
    networks:
      - tournament
    command: elasticsearch --cluster.name=tournament

networks:
  tournament:
