demo:
  image: nginx
  volumes:
    - ".:/usr/share/nginx/html"
  ports:
    - "80:80"

server:
  image: node:4.1.1
  command: sh -c "cd /var/app/server && sh run.sh"
  volumes:
    - ".:/var/app/server"

kuzzle:
  image: kuzzleio/kuzzle:0.6.0
  ports:
    - "7512:7512"
  links:
    - elasticsearch
    - redis

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2
  command: elasticsearch --cluster.name=tournament
