demo:
  image: nginx
  volumes:
    - ".:/usr/share/nginx/html"
  ports:
    - "80:80"

server:
  image: node:4.1.1
  command: sh -c "cd /var/app/server && npm start"
  volumes:
    - ".:/var/app/server"

kuzzle:
  image: kuzzleio/kuzzle:1.0.0-RC4
  ports:
    - "7512:7512"
  links:
    - elasticsearch
    - redis

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: elasticsearch:2.2
  command: elasticsearch --cluster.name=tournament
