version: '2'
services:
  front:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./www/dist:/var/www
    links:
    - kuzzle
    labels:
    - consul.service=web
    - consul.tags=mydevicess
  kuzzle:
    image: kuzzleio/kuzzle:1.2.2
    ports:
      - "7512:7512"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - redis
      - elasticsearch
    volumes:
      - "./kuzzle/mapping.json:/mapping.json"
      - "./kuzzle/fixtures.json:/fixtures.json"
      - "./kuzzle/pm2.json:/config/pm2.json"
    environment:
      - kuzzle_services__db__client__host=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - NODE_ENV=production
    labels:
    - consul.service=kuzzle
    - consul.tags=mydevices
  redis:
    image: redis:3.2
    labels:
    - consul.skip=true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - cluster.name=kuzzle
      # disable xpack
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    labels:
    - consul.skip=true